package ai

// AIRequest describes one text-generation request.
type AIRequest struct {
	// Prompt is the fully rendered text sent to the model.
	Prompt string
	// MaxTokens limits the number of tokens generated by the model.
	MaxTokens int
	// Tools lists provider-neutral function tools available to the model.
	Tools []ToolDefinition
	// ToolChoice controls whether and how the model may call tools.
	ToolChoice ToolChoice
	// ResponseFormat requests a structured response shape.
	ResponseFormat ResponseFormat
	// Reasoning configures model reasoning/thinking behavior when supported.
	Reasoning ReasoningConfig
}
