package ai

import (
	"encoding/json"
	"fmt"
)

// RequestMessage is provider-neutral native conversation history. When
// Messages is empty providers use AIRequest.Prompt as before.
type RequestMessage struct {
	Role       RequestMessageRole
	Text       string
	ToolCalls  []RequestToolCall
	ToolResult *RequestToolResult
}

type RequestMessageRole string

const (
	RequestMessageRoleUser      RequestMessageRole = "user"
	RequestMessageRoleAssistant RequestMessageRole = "assistant"
	RequestMessageRoleTool      RequestMessageRole = "tool"
)

type RequestToolCall struct {
	ID, Name  string
	Arguments json.RawMessage
}
type RequestToolResult struct {
	ToolCallID, Name, Content string
	IsError                   bool
}

func (m RequestMessage) Validate() error {
	switch m.Role {
	case RequestMessageRoleUser:
		if len(m.ToolCalls) != 0 || m.ToolResult != nil {
			return fmt.Errorf("invalid user request message")
		}
	case RequestMessageRoleAssistant:
		if m.ToolResult != nil || (m.Text == "" && len(m.ToolCalls) == 0) {
			return fmt.Errorf("invalid assistant request message")
		}
		for _, c := range m.ToolCalls {
			if c.ID == "" || c.Name == "" || !json.Valid(c.Arguments) {
				return fmt.Errorf("invalid request tool call")
			}
		}
	case RequestMessageRoleTool:
		if m.ToolResult == nil || m.Text != "" || len(m.ToolCalls) != 0 || m.ToolResult.ToolCallID == "" || m.ToolResult.Name == "" {
			return fmt.Errorf("invalid tool request message")
		}
	default:
		return fmt.Errorf("invalid request message role %q", m.Role)
	}
	return nil
}

func (r AIRequest) ValidateMessages() error {
	seen := map[string]struct{}{}
	for _, m := range r.Messages {
		if err := m.Validate(); err != nil {
			return err
		}
		switch m.Role {
		case RequestMessageRoleAssistant:
			for _, c := range m.ToolCalls {
				if _, ok := seen[c.ID]; ok {
					return fmt.Errorf("duplicate request tool call ID %q", c.ID)
				}
				seen[c.ID] = struct{}{}
			}
		case RequestMessageRoleTool:
			if _, ok := seen[m.ToolResult.ToolCallID]; !ok {
				return fmt.Errorf("tool result references unknown tool call %q", m.ToolResult.ToolCallID)
			}
		}
	}
	return nil
}

func (r AIRequest) Copy() AIRequest {
	r.Messages = append([]RequestMessage(nil), r.Messages...)
	for i := range r.Messages {
		r.Messages[i].ToolCalls = append([]RequestToolCall(nil), r.Messages[i].ToolCalls...)
		for j := range r.Messages[i].ToolCalls {
			r.Messages[i].ToolCalls[j].Arguments = append(json.RawMessage(nil), r.Messages[i].ToolCalls[j].Arguments...)
		}
		if x := r.Messages[i].ToolResult; x != nil {
			y := *x
			r.Messages[i].ToolResult = &y
		}
	}
	return r
}

// AIRequest describes one text-generation request.
type AIRequest struct {
	// Prompt is the fully rendered text sent to the model.
	Prompt string
	// Messages is opt-in provider-native history; Prompt remains the rendered fallback.
	Messages []RequestMessage
	// MaxTokens limits the number of tokens generated by the model.
	MaxTokens int
	// Tools lists provider-neutral function tools available to the model.
	Tools []ToolDefinition
	// ToolChoice controls whether and how the model may call tools.
	ToolChoice ToolChoice
	// ResponseFormat requests a structured response shape.
	ResponseFormat ResponseFormat
	// Reasoning configures model reasoning/thinking behavior when supported.
	Reasoning ReasoningConfig
}
