package ai

// AIRequest describes one text-generation request.
type AIRequest struct {
	// Prompt is the fully rendered text sent to the model.
	Prompt string
	// MaxTokens limits the number of tokens generated by the model.
	MaxTokens int
}
