package ai

import "encoding/json"

// AIResponse is the accumulated result of a non-streaming generation request.
type AIResponse struct {
	// Text contains the generated response text.
	Text string
	// Reasoning contains model reasoning/thinking text when exposed separately.
	Reasoning string
	// ToolCalls contains structured tool calls produced by the model.
	ToolCalls []ToolCall
	// Raw contains the provider response payload when retained by an implementation.
	Raw json.RawMessage
	// InputTokens is the number of prompt tokens consumed by the model.
	InputTokens int
	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int
	// ReasoningTokens is the number of reasoning/thought tokens reported by the model.
	ReasoningTokens int
}

// TokenType identifies the semantic kind of a streamed token.
type TokenType string

var (
	// TokenTypeText identifies user-visible generated text.
	TokenTypeText TokenType = "text"
	// TokenTypeThought identifies model reasoning content.
	TokenTypeThought TokenType = "thought"
	// TokenTypeToolCall identifies a structured request to invoke a tool.
	TokenTypeToolCall TokenType = "tool_call"
	// TokenTypeErr identifies an error emitted through the token stream.
	TokenTypeErr TokenType = "error"
)

// Token is one event emitted by Model.GenerateStream.
//
// Data contains the raw provider payload for text-like tokens. Text contains
// normalized text when the provider exposes it separately. ToolCall and Err are
// populated for their corresponding token types.
type Token struct {
	// Type identifies how the token should be interpreted.
	Type TokenType
	// Data contains the token's raw byte representation.
	Data []byte
	// TokenUsage is the output-token usage attributed to this event.
	TokenUsage int

	// ToolCall contains the structured call for TokenTypeToolCall.
	ToolCall *ToolCall
	// Text contains normalized text when available.
	Text string
	// Err contains the stream error for TokenTypeErr.
	Err error
}

// String returns the token's raw Data as a string.
func (t Token) String() string {
	return string(t.Data)
}

// AppendToken incorporates a streamed token into the response text and output
// token count.
func (r *AIResponse) AppendToken(t Token) {
	switch t.Type {
	case TokenTypeText:
		if len(t.Text) > 0 {
			r.Text += t.Text
		} else {
			r.Text += string(t.Data)
		}
	case TokenTypeThought:
		if len(t.Text) > 0 {
			r.Reasoning += t.Text
		} else {
			r.Reasoning += string(t.Data)
		}
		r.ReasoningTokens += t.TokenUsage
	case TokenTypeErr:
		if t.Err != nil {
			r.Text += string(t.Err.Error())
		} else {
			r.Text += string(t.Data)
		}
	case TokenTypeToolCall:
		if t.ToolCall != nil {
			tc := *t.ToolCall
			tc.Args = append([]byte(nil), t.ToolCall.Args...)
			r.ToolCalls = append(r.ToolCalls, tc)
		}
	}

	r.OutputTokens += t.TokenUsage
}
