package ai

import (
	"context"
	"encoding/json"
)

// AIResponse is the accumulated result of a non-streaming generation request.
type AIResponse struct {
	// Text contains the generated response text.
	Text string
	// Reasoning contains model reasoning/thinking text when exposed separately.
	Reasoning string
	// ToolCalls contains structured tool calls produced by the model.
	ToolCalls []ToolCall
	// Raw contains the provider response payload when retained by an implementation.
	Raw json.RawMessage
	// FinishReason identifies why the provider stopped generation when exposed.
	FinishReason string
	// InputTokens is the number of prompt tokens consumed by the model.
	InputTokens int
	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int
	// ReasoningTokens is the number of reasoning/thought tokens reported by the model.
	ReasoningTokens int
}

// Usage is normalized provider token accounting for one completed request.
type Usage struct {
	InputTokens         int
	OutputTokens        int
	ReasoningTokens     int
	CachedTokens        int
	CacheCreationTokens int
	ToolUseTokens       int
}

// Add accumulates another provider usage record.
func (u *Usage) Add(other Usage) {
	u.InputTokens += other.InputTokens
	u.OutputTokens += other.OutputTokens
	u.ReasoningTokens += other.ReasoningTokens
	u.CachedTokens += other.CachedTokens
	u.CacheCreationTokens += other.CacheCreationTokens
	u.ToolUseTokens += other.ToolUseTokens
}

// Completion is terminal metadata emitted by a streaming provider request.
type Completion struct {
	Usage Usage
	// UsageReported distinguishes an absent provider usage block from a
	// provider-reported usage block whose counters are all zero.
	UsageReported bool
	FinishReason  string
	RequestID     string
	Provider      string
	Model         string
	Raw           json.RawMessage
}

// TokenType identifies the semantic kind of a streamed token.
type TokenType string

var (
	// TokenTypeText identifies user-visible generated text.
	TokenTypeText TokenType = "text"
	// TokenTypeThought identifies model reasoning content.
	TokenTypeThought TokenType = "thought"
	// TokenTypeToolCall identifies a structured request to invoke a tool.
	TokenTypeToolCall TokenType = "tool_call"
	// TokenTypeErr identifies an error emitted through the token stream.
	TokenTypeErr TokenType = "error"
	// TokenTypeCompletion identifies terminal provider metadata for a completed stream.
	TokenTypeCompletion TokenType = "completion"
)

// Token is one event emitted by Model.GenerateStream.
//
// Data contains the raw provider payload for text-like tokens. Text contains
// normalized text when the provider exposes it separately. ToolCall and Err are
// populated for their corresponding token types.
type Token struct {
	// Type identifies how the token should be interpreted.
	Type TokenType
	// Data contains the token's raw byte representation.
	Data []byte
	// TokenUsage is the output-token usage attributed to this event.
	TokenUsage int

	// ToolCall contains the structured call for TokenTypeToolCall.
	ToolCall *ToolCall
	// Text contains normalized text when available.
	Text string
	// Err contains the stream error for TokenTypeErr.
	Err error
	// Completion contains terminal provider metadata for TokenTypeCompletion.
	Completion *Completion
}

// String returns the token's raw Data as a string.
func (t Token) String() string {
	return string(t.Data)
}

// SendToken forwards token unless ctx is canceled. It returns false when the
// receiver can no longer be reached because ctx ended.
func SendToken(ctx context.Context, out chan<- Token, token Token) bool {
	select {
	case out <- token:
		return true
	case <-ctx.Done():
		return false
	}
}

// AppendToken incorporates a streamed token into the response text and output
// token count.
func (r *AIResponse) AppendToken(t Token) {
	switch t.Type {
	case TokenTypeText:
		if len(t.Text) > 0 {
			r.Text += t.Text
		} else {
			r.Text += string(t.Data)
		}
	case TokenTypeThought:
		if len(t.Text) > 0 {
			r.Reasoning += t.Text
		} else {
			r.Reasoning += string(t.Data)
		}
		r.ReasoningTokens += t.TokenUsage
	case TokenTypeErr:
		if t.Err != nil {
			r.Text += string(t.Err.Error())
		} else {
			r.Text += string(t.Data)
		}
	case TokenTypeToolCall:
		if t.ToolCall != nil {
			tc := *t.ToolCall
			tc.Args = append([]byte(nil), t.ToolCall.Args...)
			tc.ThoughtSignature = append([]byte(nil), t.ToolCall.ThoughtSignature...)
			r.ToolCalls = append(r.ToolCalls, tc)
		}
	case TokenTypeCompletion:
		if t.Completion != nil {
			if t.Completion.UsageReported {
				r.InputTokens = t.Completion.Usage.InputTokens
				r.OutputTokens = t.Completion.Usage.OutputTokens
				r.ReasoningTokens = t.Completion.Usage.ReasoningTokens
			}
			r.FinishReason = t.Completion.FinishReason
			r.Raw = append(r.Raw[:0], t.Completion.Raw...)
		}
		return
	}

	r.OutputTokens += t.TokenUsage
}
